name: Swift Package

on: [push]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 16.4
      run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
